version: '3.8'

services:
  web:
    build: ./bookingsite
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookingsite/:/usr/src/bookingsite/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=os.environ['POSTGRES_USER']
      - POSTGRES_PASSWORD=os.environ['hello_django']
      - POSTGRES_DB=os.environ['hello_django_dev']

volumes:
  postgres_data:
