# Generated by Django 5.0.1 on 2024-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
